### ISSUE TITLE
14. Member posts status (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wkhammond** [comment]
Member Jim wants to post a status so that other people can see his controversial opinions:
- Jim navigates to the Members Only site in his browser and logs in, bringing him to the home page
- Jim sees text box for posting a status and clicks it
- Jim writes status (containing his controversial opinion)
- Jim clicks post button
- The server saves post and adds it to the list of posts from that user, and Jim's status is posted (goal achieved)
