### ISSUE TITLE
15. Member updates profile (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#19]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wkhammond** [comment]
Member Jan wants to edit her profile so that it stays up-to-date:
- Jan navigates to Members Only and logs in 
- Jan clicks on her name
- Jan is taken to her profile
- Jan clicks the edit button
- Jan alters details of their profile
- Jan clicks the "save changes" button
- Server commits changes to member profile
- Jan is taken to home screen with her updated profile (goal achieved)
