### ISSUE TITLE
16. System charges credit card an amount (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wkhammond** [comment]
The system charges member Ryan's card because it has been a month since his last transaction:
- System randomly determines amount to charge (between 20 and 45 cents)
- Payment processor charges card and reports whether or not it was approved
If payment approved:
- Server notes date, time, and amount of transaction into user history (to potentially verify later) (goal achieved)
If payment denied:
- Server marks account as "not in good standing" (goal not achieved)
