### ISSUE TITLE
17. Member toggles account to private 

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#21]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wkhammond** [comment]
Member Dwight wants to make his profile private, because he is sick of being stalked by his ex (who he did not invite to Members Only):
- Dwight navigates to Members Only and logs in
- Dwight clicks the settings button in the corner (cog symbol)
- Dwight goes to the settings page
- Under Privacy, Dwight selects option to "Make account private"
- Server sets user account to "private"
- Dwight is returned to the home page with his newly privatized account (goal achieved)
