### ISSUE TITLE
19. Member signs in (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#23]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wkhammond** [comment]
Michael wants to log in to Members Only so he can stalk the employees he invited:
- Michael navigates to the Members Only login page on his web browser
- Michael enters in his email address into the "email address" box
- Michael enters in his password into the "password" box
- Server verifies user information
If information is correct:
- Michael is logged in and moved to the home page
If information is incorrect:
- Michael is either told that their information is invalid
If Michael's account is "not in good standing" (due to a credit card decline):
- Michael is taken to the payment verification screen
