### ISSUE TITLE
23. Admin adds sponsored content (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#27]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JacksonWeber** [comment]
An Administrator wants to add sponsored content to a photo that a member (Fred) has posted.

The Admin downloads the image and preforms the desired changes.

The Admin then reuploads the image so that the edited image will be viewed by any other member currently seeing Fred's posts in their feed. (goal achieved)
